-- MySQL Script generated by MySQL Workbench
-- Mon Nov 26 18:12:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`major` ;

CREATE TABLE IF NOT EXISTS `mydb`.`major` (
  `major_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`major_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hometown_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hometown_location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hometown_location` (
  `location_id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`laptop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`laptop` ;

CREATE TABLE IF NOT EXISTS `mydb`.`laptop` (
  `laptop_id` INT NOT NULL,
  `screen_size` DECIMAL(3,1) NOT NULL,
  `brand` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  PRIMARY KEY (`laptop_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`survey_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`survey_location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`survey_location` (
  `survey_location_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`survey_location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `person_id` INT NOT NULL,
  `major_id` INT NOT NULL,
  `hometown_location_id` INT NOT NULL,
  `laptop_id` INT NOT NULL,
  `laptop_purchased_dt` DATETIME NULL,
  `laptop_picture_url` VARCHAR(50) NULL,
  `likelihood_to_buy_more` INT NULL,
  `likelihood_to_put_more` INT NULL,
  `survey_location_id` INT NOT NULL,
  PRIMARY KEY (`person_id`),
  INDEX `fk_person_major_idx` (`major_id` ASC),
  INDEX `fk_person_location1_idx` (`hometown_location_id` ASC),
  INDEX `fk_person_laptop1_idx` (`laptop_id` ASC),
  INDEX `fk_person_survey_location1_idx` (`survey_location_id` ASC),
  CONSTRAINT `fk_person_major`
    FOREIGN KEY (`major_id`)
    REFERENCES `mydb`.`major` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_location1`
    FOREIGN KEY (`hometown_location_id`)
    REFERENCES `mydb`.`hometown_location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_laptop1`
    FOREIGN KEY (`laptop_id`)
    REFERENCES `mydb`.`laptop` (`laptop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_survey_location1`
    FOREIGN KEY (`survey_location_id`)
    REFERENCES `mydb`.`survey_location` (`survey_location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`color` ;

CREATE TABLE IF NOT EXISTS `mydb`.`color` (
  `color_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`color_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brand_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sticker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sticker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sticker` (
  `sticker_id` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `width` INT NULL,
  `height` INT NULL,
  `color_id` INT NOT NULL,
  `price` INT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`sticker_id`),
  INDEX `fk_sticker_color1_idx` (`color_id` ASC),
  INDEX `fk_sticker_brand1_idx` (`brand_id` ASC),
  CONSTRAINT `fk_sticker_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `mydb`.`color` (`color_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sticker_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `mydb`.`brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_has_sticker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`person_has_sticker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`person_has_sticker` (
  `person_id` INT NOT NULL,
  `sticker_id` INT NOT NULL,
  PRIMARY KEY (`person_id`, `sticker_id`),
  INDEX `fk_person_has_sticker_sticker1_idx` (`sticker_id` ASC),
  INDEX `fk_person_has_sticker_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_person_has_sticker_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_sticker_sticker1`
    FOREIGN KEY (`sticker_id`)
    REFERENCES `mydb`.`sticker` (`sticker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
